#!/bin/bash
sudo apt-get install -y git-core
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
which git
which heroku
git config --global user.name "wheaton5"
got config --global user.email "whheaton@gmail.com"
